"""Add rating column to favorite table

Revision ID: 573d3bd6ffba
Revises: c0baa0b50705
Create Date: 2024-07-22 13:59:42.460181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573d3bd6ffba'
down_revision = 'c0baa0b50705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite', 'rating')
    # ### end Alembic commands ###
